version: '2'

services:
  postgres:
    image: postgres:10.8
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    restart: always
  web:
    depends_on:
      - postgres
    image: rest-service
    ports:
      - "8080:8080"
    restart: always
    links:
      - postgres